<?php



function xproject_preferences_user($op, $edit, &$account, $category = NULL) {
    global $user;
    
    switch ($op) {
        case 'register':
            /* do not collect during registration
            $form['xcontact'] = array(
                '#type' => 'select', 
                '#title' => t('Default Contact'), 
                '#options' => xcontact_get_all_contact(),
                '#description' => t('Select default Contact'),
                );
    		return $form;
            */
    		break;
        case 'insert':
    	
    		xproject_preferences_add($account->uid,$edit['xcontact']);
    		break;
        case 'delete':
    		xproject_preferences_delete($account->uid);
    		break;
        case 'load':
        
            break;
        case 'view':
          
            break;
        case 'form':
//            print_r($user);
        	$form['xcontact'] = array(
                '#type' => 'select', 
                '#title' => t('Default Contact'), 
                '#options' => xcontact_get_my_contacts(),
                '#default_value' => $user->xcontact,
                '#description' => t('Select a default contact record to use for assigning tasks to.'),
                );
            return $form;
            break;
        case 'validate':
            if(!$user->xcontact) {
    		    xproject_preferences_add($account->uid,$edit['xcontact']);
            }
            break;
    }
}

function xproject_preferences_add($uid,$xcontactid) {
	if($uid && $xcontactid) {
		$sql = "INSERT INTO xproject_preferences (uid,default_contactid) 
		VALUES($uid,$xcontactid)";
		db_query($sql);
	} else {
		drupal_set_message('xcontact is not saved for this user');
    }
}

function xproject_preferences_delete($uid) {
	if($uid) {
		$sql = "DELETE from xproject_preferences WHERE uid = ".$uid;
		db_query($sql);
	} else {
		drupal_set_message('xcontact is not deleted for this user');
    }
}

?>