<?php
function xtasks_menu() {
  $items = array();

  $items['node/%xproject_projectid/tasks/add'] = array(
    'title' => 'add tasks', 
    'description' => 'Used to add tasks to a project', 
    'page callback' => 'drupal_get_form', 
	'page arguments' => array('xtasks_form', 1),
    'access arguments' => array('create tasks'), 
    'type' => MENU_SUGGESTED_ITEM,
  );
  $items['xtasks'] = array(
		'page callback' => 'xtasks_page',
		'access arguments' => array('create tasks'),
		'title' =>'Tasks',
		'type' => MENU_NORMAL_ITEM ,
		'weight' => 10
	);
	
    return $items;
}
function xtasks_perm() {
    return array(
        'create tasks' => array(
          'title' => t('create project tasks'), 
          'description' => t('Permission to create tasks'),
        ),
      );
}


function xtasks_link($type, $object, $teaser = FALSE) {
  $links = array();

    if ($type == 'node' && xproject_is_xproject($object->type)) {
        if (!$teaser) {
            $links['xtasks_add_task'] = array(
              'title' => t('add task'), 
              'href' => 'node/'.$object->nid.'/tasks/add',
            );
            
            $links['xtasks_task_list'] = array(
              'title' => t('task list'), 
              'href' => 'node/'.$object->nid.'/tasks/list',
              'attributes' => array('title' => t('List of tasks assigned to this project.')),
            );
        }
    }
    return $links;
}

function xtasks_form($form_state) {

    $form['taskname'] = array(
        '#type' => 'textfield', 
        '#title' => t('Task title'),
        '#required' => TRUE,
      );
  $form['taskdetails'] = array(
    '#type' => 'textarea', 
    '#title' => 'task description', 
    '#rows' => 20, 
    '#required' => TRUE,
  );
  $form['taskstatus'] = array(
    '#type' => 'select', 
    '#title' => t('Status'), 
    '#default_value' => $node->status, 
    '#options' => array(
      1 => 'Draft', 
      2 => 'Pending', 
	  3 => 'Active',
      4 => 'Archived',
    ), 
    '#description' => t('Staus of task'),
  );
  	$form['taskimportance'] = array(
        '#type' => 'select', 
        '#title' => t('Importance'), 
        '#default_value' => $data['taskimportance'], 
        '#options' => array(
            1 => 1, 
            2 => 2, 
            3 => 3,
            4 => 4,
            5 => 5,
            6 => 6,
            7 => 7,
            8 => 8,
            9 => 9,
        ), 
        '#description' => t('level of task importance'),
        );
	$form['private'] = array(
		'#type' =>'checkbox', 
		'#title' => t('Private'),
		'#default_value' => $data['private']);
	$form['hours_planned'] = array(
		'#type' => 'textfield', 
		'#title' => t('Hours planned'), 
		'#default_value' =>$data['hours_planned'] , 
		'#size' =>6 , 
		'#maxlength' => 16, );
	$form['hours_spent'] = array(
		'#type' => 'textfield', 
		'#title' => t('Hours spent'), 
		'#default_value' =>$data['hours_spent'] , 
		'#size' =>6 , 
		'#maxlength' => 16, );
	$form['hours_remaining'] = array(
		'#type' => 'textfield', 
		'#title' => t('Hours remaining'), 
		'#default_value' =>$data['hours_remaining'] , 
		'#size' =>6 , 
		'#maxlength' => 16, );
	$form['date_approved'] = array(
		'#type' => 'date', 
		'#title' => 'Date approved', 
		'#default_value' => $data['date_approved'], 
		'#description' => '', );
	$form['planned_start_date'] = array(
		'#type' => 'date', 
		'#title' => 'Planned start date', 
		'#default_value' => $data['planned_start_date'], 
		'#description' => '', );
	$form['planned_end_date'] = array(
		'#type' => 'date', 
		'#title' => 'Planned end date', 
		'#default_value' => $data['planned_end_date'], 
		'#description' => '', );
	$form['actual_start_date'] = array(
		'#type' => 'date', 
		'#title' => 'Actual start date', 
		'#default_value' => $data['actual_start_date'], 
		'#description' => '', );
	$form['actual_end_date'] = array(
		'#type' => 'date', 
		'#title' => 'Actual end date', 
		'#default_value' => $data['actual_end_date'], 
		'#description' => '', );		
 
 
  $form['submit'] = array(
  '#type' => 'submit', '#value' => t('Save'));

  return $form;
}
function xtasks_form_submit($form, &$form_state) {

    $form_state['values']['planned_start_date'] = xproject_convert_date2string($form_state['values']['planned_start_date']);
    $form_state['values']['planned_end_date'] = xproject_convert_date2string($form_state['values']['planned_end_date']);
    $form_state['values']['actual_start_date'] = xproject_convert_date2string($form_state['values']['actual_start_date']);
    $form_state['values']['actual_end_date'] = xproject_convert_date2string($form_state['values']['actual_end_date']);
    $form_state['values']['date_approved'] = xproject_convert_date2string($form_state['values']['date_approved']); 
    if(drupal_write_record('xtasks', $form_state['values']))
    	drupal_set_message('A new task added');
}

function xtasks_page(){

}
 ?>