<?php

function xproject_init() {
    // We have to perform a load in order to assure that the ajax/javascript bits are present.
    
    drupal_add_css(drupal_get_path('module', 'xproject'). '/theme/xproject.css');
    drupal_add_js(drupal_get_path('module', 'xproject'). '/js/xproject.js');
}

function xproject_help($path, $arg) {
  if ($path) {
    switch ($path) {
      case ($arg[2] == 'block' && $arg[4] == 'xproject'):
        return t('Project specific blocks help...');
        break;
      case 'admin/settings/xproject':
        return t('In order to let project owners...');
        break;
    }
  }
}

/**
 * Implementation of hook_perm().
 */
function xproject_perm() {
  return array('xproject administration', 'xproject access');
}


function xproject_convert_date2string($date_array) {
    if(is_array($date_array)) {
        return $date_array['year'].'-'.$date_array['month'].'-'.$date_array['day'].' 00:00:00';
    }
}

function xproject_convert_date2array($date) {
    if(!is_string($date)) return $date;
    list($date_part, $time_part) = explode(' ', $date);
    list($year_part, $month_part, $day_part) = explode('-', $date_part);
    list($hour_part, $min_part, $sec_part) = explode(':', $time_part);
    $return_array = array('year' => (int)$year_part, 'month' => (int)$month_part, 'day' => (int)$day_part);
    return $return_array;
}

/**
 * Implementation of hook_menu().
 */
function xproject_menu() {
    $items['admin/settings/xproject'] = array(
        'type' => MENU_NORMAL_ITEM,
        'page callback' => 'drupal_get_form',
        'page arguments' => array('xproject_admin_settings'),
        'access arguments' => array('xproject administration'),
        'file' => 'xproject.admin.inc',
        'file path' => drupal_get_path('module', 'xproject'). '/includes',
        'title' => 'xProject Settings'
    );
    $items['admin/content/xproject'] = array(
        'type' => MENU_NORMAL_ITEM,
        'page callback' => 'xproject_projects',
        'page arguments' => array(2),
        'access callback' => 'node_access',
        'access arguments' => array('view', 2),
        'title' => 'xProjects'
    );
    /*
	$items['node/%xproject_node/addtasks'] = array(
    	'title' => 'Add tasks',
    	'type' => MENU_LOCAL_TASK,
    	'weight' => 10,
    	'page callback' => 'drupal_get_form',
        'page arguments' => array('xtasks_form', 1),
        'access arguments' => array('xproject administration'),
    );
    */
	$items['node/%xproject_node/teamlist'] = array(
    	'title' => 'Team List',
    	'type' => MENU_LOCAL_TASK,
    	'weight' => 10,
    	'page callback' => 'teamlist_page',
        'access arguments' => array('xproject administration'),
    );
	$items['node/%xproject_node/taskslist'] = array(
    	'title' => 'Task List',
    	'type' => MENU_LOCAL_TASK,
    	'weight' => 10,
    	'page callback' => 'xtasks_page',
        'access arguments' => array('xproject administration'),
    );
	$items['node/%xproject_node/worklog'] = array(
    	'title' => 'Worklogs',
    	'type' => MENU_LOCAL_TASK,
    	'weight' => 10,
    	'page callback' => 'xworklog_page',
        'access arguments' => array('xproject administration'),
    );

    
    return $items;
}

function xproject_node_load($nid) {
	if (is_numeric($nid) && module_exists('xtasks')) {
		$node = node_load($nid);
        if (xproject_is_xproject($node->type)) {
            return $node;
        }
    }
	return false;
}


function xproject_preprocess_node(&$variables) {
    $node = $variables['node'];
    if (xproject_is_xproject($node->type)) {
        array_unshift($variables['template_files'], 'node-xproject');
    }
}

function xproject_theme_registry_alter(&$variables) {
  // Check for xproject provided templates just before we use the default node.tpl.php
  array_splice($variables['node']['theme paths'], 1, 0, drupal_get_path('module', 'xproject'). '/theme');
}

function xproject_nodeapi(&$node, $op, $teaser = NULL, $page = NULL) {
    global $user;

    if(xproject_is_xproject($node->type) == true) {
    	$data = array();
        switch ($op) {
            case 'view':
                $node->content['project'] = array(
                  '#node' => $node,
                  '#weight' => -3,
                  '#value' => theme('xproject', $node),
                );
                
                    
//                print_r($node);
                break;
            case 'load':
                $result = db_query('SELECT * FROM xproject WHERE nid = '.$node->nid);
                if($row = db_fetch_array($result)) {
                    $row['date_approved'] = xproject_convert_date2array($row['date_approved']);
                    $row['planned_start_date'] = xproject_convert_date2array($row['planned_start_date']);
                    $row['planned_end_date'] = xproject_convert_date2array($row['planned_end_date']);
                    $row['actual_start_date'] = xproject_convert_date2array($row['actual_start_date']);
                    $row['actual_end_date'] = xproject_convert_date2array($row['actual_end_date']);
//print_r($row);
                    return $row;
                }
                break;
            case 'validate':
                break;
            case 'presave':
                break;
            case 'delete':
				$success = xproject_delete_project($node->nid);
				if(!$success)
					drupal_set_message('Error deleting xproject','error');
                break;
            case 'insert':
            case 'update':
                // will check for nid, so same code for both insert and update
                
                // drupal_write_record fails on fields with array values, so convert the dates:
                $node->planned_start_date = xproject_convert_date2string($node->planned_start_date);
                $node->planned_end_date = xproject_convert_date2string($node->planned_end_date);
                $node->actual_start_date = xproject_convert_date2string($node->actual_start_date);
                $node->actual_end_date = xproject_convert_date2string($node->actual_end_date);
                $node->date_approved = xproject_convert_date2string($node->date_approved);
                
//                print_r($node); die('test');
                $data = xproject_get_project($node->nid);
                if(isset($data['nid'])) {
			        drupal_write_record('xproject', $node,'nid');
                } else {
                    // xproject record not yet created, do so now (ex: content item after xprojects turned on for that node type)
    			    drupal_write_record('xproject', $node);
                }
                break;
            case 'search result':
                break;
            case 'rss item':
                break;
        }
	}
}

function xproject_get_project($nid) {
    $data = array();
    if ($nid) {
        $result = db_query('SELECT * FROM xproject WHERE nid = '.$nid);
        if($row = db_fetch_array($result)) {
            return $row;
        }
	}
    return array();
}
function xproject_delete_project($nid) {
    if ($nid) {
        $result = db_query('DELETE FROM xproject WHERE nid = '.$nid);
        if($result) {
            return TRUE;
        } else {
			return FALSE;
        }
	}
}


function xproject_project_form($node, $form_state) {
    global $user;
    
    $form = array();
    
    if(xproject_is_xproject($node->type) == false) {
        return $form;
    }
    
    // Set the default values for a new item. By using += rather than =, we
    // only overwrite array keys that have not yet been set. It's safe to use
    // on both an empty array, and an incoming array with full or partial data.
    $node = (array)$node;
    $node += array(
        'nid' => NULL,
    );
    $node = (object)$node;
//    print_r($node);
    // BEGIN BUILDING PROJECT FORM HERE. TITLE AND DESCRIPTION ARE HANDLED BY THE NODE ALREADY
	$form['nid'] = array('#type' => 'hidden', '#value' => $node->nid);
	$form['is_template'] = array(
		'#type' =>'checkbox', 
		'#title' => t('Is template'),
        '#default_value' => $node->is_template, 
    );
	$form['projectstatus'] = array(
        '#type' => 'select', 
        '#title' => t('Status'), 
        '#default_value' => $node->projectstatus, 
        '#options' => array(
            'Draft' => t('Draft'), 
            'Pending' => t('Pending'), 
            'Active' => t('Active'),
            'On Hold' => t('On Hold'),
            'Archived' => t('Archived'),
        ), 
        '#description' => t('Status of project'),
        '#prefix' => '<div class="project-field-row">',
        );
	$form['private'] = array(
		'#type' =>'checkbox', 
		'#title' => t('Private'),
		'#default_value' => $node->private,
        '#suffix' => '</div><div class="clear"></div>',
        );
	$form['importance'] = array(
        '#type' => 'select', 
        '#title' => t('Importance'), 
        '#default_value' => $node->importance, 
        '#options' => array(
            1 => 1, 
            2 => 2, 
            3 => 3,
            4 => 4,
            5 => 5,
            6 => 6,
            7 => 7,
            8 => 8,
            9 => 9,
        ), 
        '#description' => t('Overall level of project importance'),
        '#prefix' => '<div class="project-field-row">',
        );
	$form['priority'] = array(
        '#type' => 'select', 
        '#title' => t('Priority'), 
        '#default_value' => $node->priority, 
        '#options' => array(
            1 => 1, 
            2 => 2, 
            3 => 3,
            4 => 4,
            5 => 5,
            6 => 6,
            7 => 7,
            8 => 8,
            9 => 9,
        ), 
        '#description' => t('Current priority of the project'),
        '#suffix' => '</div><div class="clear"></div>',
        );

    $form['project_hours'] = array(
        '#type' => 'fieldset',
        '#title' => t('Project Hours'),
        '#collapsible' => true,
        '#collapsed' => true,
    );
	$form['project_hours']['hours_planned'] = array(
		'#type' => 'textfield', 
		'#title' => t('Hours planned'), 
		'#default_value' =>$node->hours_planned, 
		'#size' =>6 , 
		'#maxlength' => 16,
        '#prefix' => '<div class="project-field-row">', );
	$form['project_hours']['hours_spent'] = array(
		'#type' => 'textfield', 
		'#title' => t('Hours spent'), 
		'#default_value' =>$node->hours_spent, 
		'#size' =>6 , 
		'#maxlength' => 16, );
	$form['project_hours']['hours_remaining'] = array(
		'#type' => 'textfield', 
		'#title' => t('Hours remaining'), 
		'#default_value' =>$node->hours_remaining, 
		'#size' =>6 , 
		'#maxlength' => 16,
        '#suffix' => '</div><div class="clear"></div>', );
	

    $form['project_dates'] = array(
        '#type' => 'fieldset',
        '#title' => t('Project Dates'),
        '#collapsible' => true,
        '#collapsed' => true,
    );
	$form['project_dates']['date_approved'] = array(
		'#type' => 'date', 
		'#title' => 'Date approved', 
		'#default_value' => $node->date_approved, 
		'#description' => '',
    );
	$form['project_dates']['planned_start_date'] = array(
		'#type' => 'date', 
		'#title' => 'Planned start date', 
		'#default_value' => $node->planned_start_date, 
		'#description' => '',
        '#prefix' => '<div class="project-field-row">', );
	$form['project_dates']['planned_end_date'] = array(
		'#type' => 'date', 
		'#title' => 'Planned end date', 
		'#default_value' => $node->planned_end_date, 
		'#description' => '',
        '#suffix' => '</div><div class="clear"></div>', );
	$form['project_dates']['actual_start_date'] = array(
		'#type' => 'date', 
		'#title' => 'Actual start date', 
		'#default_value' => $node->actual_start_date, 
		'#description' => '',
        '#prefix' => '<div class="project-field-row">', );
	$form['project_dates']['actual_end_date'] = array(
		'#type' => 'date', 
		'#title' => 'Actual end date', 
		'#default_value' => $node->actual_end_date, 
		'#description' => '',
        '#suffix' => '</div><div class="clear"></div>', );
    return $form;
}

function xproject_form_alter(&$form, &$form_state, $form_id) {

    if (isset($form['#node']) && $form_id == $form['#node']->type .'_node_form') {
        $node = $form['#node'];
//print_r($form);
        if (xproject_is_xproject($node->type)) {

            $form = array_merge($form, xproject_project_form($node, $form_state));
            // Don't trample on custom label.
			 if (isset($form['title']) && $form['title']['#title'] == t('Title'))
			 {
				$form['title']['#title'] = t('Project Name');
			 }
            if (isset($form['body_field']) && $form['body_field']['body']['#title'] == t('Body')) 	
			{
                $form['body_field']['body']['#title'] = t('Project Details');
            }
            $form['author']['name']['#title'] = t('Project manager');
        }
    } elseif ($form_id == 'node_type_form') {
        $form['xproject'] = array(
          '#type' => 'fieldset',
          '#title' => t('xProject'),
          '#group' => 'additional_settings',
          '#collapsible' => TRUE,
          '#collapsed' => TRUE,
          '#weight' => 32,
        );
        $form['xproject']['xproject_use'] = array(
          '#type' => 'checkbox',
          '#title' => t('Use this content type as a project'),
          '#default_value' => variable_get('xproject_use_'. $form['#node_type']->type, FALSE),
        );
    }
}

/**
 * Implementation of hook_node_type().
 * Rename or delete the settings variable if a type changes.
 */
function xproject_node_type($op, $info) {
    switch ($op) {
        case 'delete':
            variable_del('xproject_use_'. $info->type);
            variable_del('xproject_'. $info->type);
            break;
        case 'update':
            if (!empty($info->old_type) && $info->old_type != $info->type) {
                if (xproject_is_xproject($info->old_type)) {
                    $settings = variable_get('xproject_'. $info->old_type, array());
                    variable_del('xproject_use_'. $info->old_type);
                    variable_del('xproject_'. $info->old_type);
                    variable_set('xproject_use_'. $info->type, 1);
                    variable_set('xproject_'. $info->type, $settings);
                }
            }
            break;
    }
}

function xproject_user($op, $edit, &$account, $category = NULL) {
  global $user;

  switch ($op) {
    case 'register':
    
      break;
    case 'insert':
    
      break;
    case 'delete':
    
      break;
    case 'load':
    
      break;
    case 'view':
      
      break;
  }
}

function xproject_get_types() {
    $types = node_get_types();
    foreach ($types as $type) {
        $type_usage = variable_get('xproject_use_'. $type->type, 0);
        $return[$type->type] = $type_usage;
    }
    return isset($return) ? $return : array();
}

function xproject_is_xproject($type) {
    if (is_object($type)) {
        $type = $type->type;
    }
    return variable_get('xproject_use_'. $type, FALSE);
}

function xproject_block($op = 'list', $delta = 0, $edit = array()) {

}

/**
 * Implementation of hook_theme().
 */
function xproject_theme() {
    $path = drupal_get_path('module', 'xproject');
    return array(
        'xproject' => array(
            'template' => 'xproject',
            'arguments' => array('node' => false),
            'path' => "$path/theme",
        ),
    );
}

/**
 * Implementation of hook_views_api().
 */
function xproject_views_api() {
  return array(
    'api' => 2,
	'path' => drupal_get_path('module', 'xproject'),
  );
}
?>